### ISSUE TITLE
colored text

### ISSUE THREAD

**Issue by ValkTheBoxman** [ValkTheBoxman/boxpyShell#8]
(if it even is possible)

**Comment by ValkTheBoxman** [comment]
Not possible

**Comment by Gusic06** [comment]
(it is possible)

**Comment by ValkTheBoxman** [comment]
https://stackoverflow.com/questions/287871/how-do-i-print-colored-text-to-the-terminal

Could use curses.

**Comment by ValkTheBoxman** [comment]
https://stackoverflow.com/questions/287871/how-do-i-print-colored-text-to-the-terminal

> Could use curses or termcolor

**Comment by ValkTheBoxman** [comment]
fixed in color patch 1
